Initial tests adjusted to the service:
PassengerControllerIt test is not working because of
java.lang.IllegalStateException: Failed to load ApplicationContext for
[WebMergedContextConfiguration@737e4a7b testClass =
pl.flywithbookedseats.passengeraccountservice.api.PassengerControllerIT,
locations = [], classes =
[pl.flywithbookedseats.PassengerAccountServiceApplication], conte which
is caused in TARGET location.... no idea why ?

StorageArchitectureTest is not passing because of old useless mapper
classes which will be deleted.

Signed-off-by: Kamil Laganowski <laganowski.kamil@gmail.com>